version: 2

ANCHORS:
  node_steps: &node_steps
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule update --init --recursive
      - run: npm install
      # Check whether "run build" is successful
      - run: npm run build
      - run: npm run test

jobs:
  node_10:
    docker:
      - image: circleci/node:10
      - image: selenium/standalone-chrome-debug:3.141.59
    <<: *node_steps

  node_8:
    docker:
      - image: circleci/node:8
      - image: selenium/standalone-chrome-debug:3.141.59
    <<: *node_steps

  gh_page_deploy:
    docker:
      - image: circleci/node:10
    environment:
      GIT_AUTHOR_EMAIL: nwtgck.bee@gmail.com
      GIT_AUTHOR_NAME: "Bee Bot"
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule update --init --recursive
      # Setting to push as @bee-bot
      - run: git config user.email "$GIT_AUTHOR_EMAIL"
      - run: git config user.name "$GIT_AUTHOR_NAME"
      - run: git remote set-url origin https://${GITHUB_TOKEN}@github.com/nwtgck/nipp.git

      - run: npm install
      - run: npm run deploy

workflows:
  version: 2
  node_tests:
    jobs:
      - node_10:
          filters:
            branches:
              only: /.*/
      - node_8:
          filters:
            branches:
              only: /.*/
      - gh_page_deploy:
          requires:
            - node_10
            - node_8
          filters:
            branches:
              only:
                - master
